### ISSUE TITLE
Error: is not a valid command name

### ISSUE THREAD

**Issue by mrjakew** [leojahrens/scatterfit#1]
Hi,

This looks like a great package. Unfortunately I am getting an error message.

net install scatterfit, from(https://raw.githubusercontent.com/leojahrens/scatterfit/master) replace
checking scatterfit consistency and verifying not already installed...
all files already exist and are up to date.

scatterfit weight length
﻿ is not a valid command name
(error occurred while loading scatterfit.ado)
r(199);

I am no expert in STATA. Apologies if I have made a simple mistake.
Thanks

**Comment by leojahrens** [comment]
Hi,

thank you for the feedback!

Reinstall the command, my version 1.1 broke the program, sorry. The updated version should work. Please tell me if things are fine now. 

net install scatterfit, from(https://raw.githubusercontent.com/leojahrens/scatterfit/master) replace

Best wishes
Leo

**Comment by mrjakew** [comment]
Thanks a lot for the quick update! It seems to be working now :)
